// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpesvglraqgxnfqfvhyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZXN2Z2xyYXFneG5mcWZ2aHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzg5MzAsImV4cCI6MjA3MjM1NDkzMH0.aqx5J_4rl3_uA_Gzka7ayR93W52i2x580oUL2cv7sFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});